version: "3.3"
services:
  pythos-webui:
    build:
      context: .
      args:
        # Requirements file to use: 
        # | GPU | CPU | requirements file to use |
        # |--------|---------|---------|
        # | NVIDIA | has AVX2 | `requirements.txt` |
        # | NVIDIA | no AVX2 | `requirements_noavx2.txt` |
        # | AMD | has AVX2 | `requirements_amd.txt` |
        # | AMD | no AVX2 | `requirements_amd_noavx2.txt` |
        # | CPU only | has AVX2 | `requirements_cpu_only.txt` |
        # | CPU only | no AVX2 | `requirements_cpu_only_noavx2.txt` |
        # | Apple | Intel | `requirements_apple_intel.txt` |
        # | Apple | Apple Silicon | `requirements_apple_silicon.txt` |
        Default: requirements.txt`
        BUILD_REQUIREMENTS: requirements.txt
        
        # Extension requirements to build: 
        # BUILD_EXTENSIONS: 
        
        # specify which cuda version your card supports: https://developer.nvidia.com/cuda-gpus
        TORCH_CUDA_ARCH_LIST: ${TORCH_CUDA_ARCH_LIST:-7.5;8.6+PTX}
        BUILD_EXTENSIONS: ${BUILD_EXTENSIONS:-}
        #APP_GID: ${APP_GID:-6972} 
        #APP_UID: ${APP_UID-6972} 
        APP_GID: ${APP_GID:-1000} 
        APP_UID: ${APP_UID-1000} 
    env_file: .env
    mem_limit: "48G"
    user: "${APP_RUNTIME_UID:-1000}:${APP_RUNTIME_GID:-1000}"
    ports:
      - "${HOST_PORT:-7860}:${CONTAINER_PORT:-7860}"
      - "${HOST_API_PORT:-5000}:${CONTAINER_API_PORT:-5000}"
    stdin_open: true
    tty: true
    volumes:
      # Long term memory with quadrant https://github.com/jason-brian-anderson/long_term_memory_with_qdrant/blob/main/docker-compose.yml
      - ./extensions/settinx:/app/qdrant
      - ./extensions/settings.yaml:/app/settings.yaml
      - ./cache:/home/app/pythos-webui/cache
      - ./installer_file:/home/app/pythos-webui/installer_file
      - ./characters:/home/app/pythos-webui/characters
      - ./extensions:/home/app/pythos-webui/extensions
      - ./loras:/home/app/pythos-webui/loras
      - ./logs:/home/app/pythos-webui/logs
      - ./models:/home/app/pythos-webui/models
      - ./presets:/home/app/pythos-webui/presets
      - ./prompts:/home/app/pythos-webui/prompts
      - ./softprompts:/home/app/pythos-webui/softprompts
      - ./training:/home/app/pythos-webui/training
      - ./cloudflared:/etc/cloudflared
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              options: 
                profile: "1"  # Profilul de performanță al GPU-ului
                memory: "8G"  # Setează 6 GB pentru VRAM
    networks:
      coozila_private_network:

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    env_file: .env
    ports:
      - "6333:6333"
    volumes:
      - ./extensions/long_term_memory/qdrant:/app/qdrant
    networks:
      coozila_private_network:

networks:
  coozila_private_network:
    external: true
